# Generated by Django 3.2.19 on 2024-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('imgUrl', models.ImageField(upload_to='blog-images/')),
                ('description', models.TextField()),
                ('quote', models.TextField()),
            ],
        ),
    ]
