# Generated by Django 3.2.19 on 2024-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking', '0002_auto_20240906_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
