# Generated by Django 3.2.19 on 2024-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking', '0005_remove_car_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
