# Generated by Django 3.2.19 on 2024-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking', '0006_car_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
